project: artefacts/omnilrs
version: 0.1.0

jobs:
  test-startup:
    type: test
    timeout: 15 # minutes
    package:
      docker:
        build:
          dockerfile: ./artefacts.Dockerfile
    runtime:
      framework: other
      simulator: isaacsim
      
    scenarios:
      settings:
        - name: test_ros2_sanity
          run: "pixi run test-ros2"
        - name: test_yamcs_sanity
          run: "pixi run test-yamcs"
  
  test-vulkan:
    type: test
    timeout: 15 # minutes
    package:
      docker:
        build:
          dockerfile: ./artefacts.Dockerfile
    runtime:
      framework: other
      simulator: isaacsim
      
    scenarios:
      settings:
        - name: test_vulkan_icd
          run: "pixi run test-vulkan-icd"

  