[workspace]
authors = [
    "Shamistan Karimov <ahresgg@gmail.com>",
    "Elian Neppel",
    "Bach Nguyen",
]
channels = ["conda-forge"]
name = "OmniLRS"
platforms = ["linux-64"]
version = "0.1.0"
description = "Pixi environments for OmniLRS with Isaac Sim 5 and manager-specific features"

[system-requirements]
libc = { family = "glibc", version = "2.35" }

[tasks]
dedup-envs = "rdfind -makehardlinks true .pixi/envs"

[pypi-options]
index-url = "https://pypi.org/simple"
extra-index-urls = ["https://pypi.nvidia.com"]
index-strategy = "unsafe-best-match"

# common deps, tasks, env variables in feature "core"
[feature.core.dependencies]
python = "3.11.*"
gdal = "*"
libgdal = "*"
libglu = "*"
rdfind = "*"

[feature.core.pypi-dependencies]
opencv-python = "*"
omegaconf = "*"
hydra-core = "*"
skyfield = "*"
zfpy = "*"
numba = "*"
gdown = "*"
em = "*"
lark = "*"
pandas = "*"
OmniLRS = { path = ".", editable = true }

[feature.core.activation.env]
OMNILRS_ROOT = "${PIXI_PROJECT_ROOT}"
LD_LIBRARY_PATH = "$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"

# isaacsim-specific deps, tasks, env variables in feature "isaac"
[feature.isaac.dependencies]
packaging = "==23.0"
numpy = "==1.26.0"

[feature.isaac.pypi-dependencies]
isaacsim = { version = "==5.0.0", extras = ["all", "extscache"] }

[feature.isaac.activation.env]
OMNI_KIT_ACCEPT_EULA = "YES"

[feature.isaac.tasks]
isaacsim = "isaacsim"

# ros2-specific tasks, env variables in feature "ros2"
[feature.ros2.activation]
scripts = ["scripts/activate_isaac_ros.sh"]

[feature.ros2.activation.env]
ROS_DISTRO = "humble"
RMW_IMPLEMENTATION = "rmw_fastrtps_cpp"

[feature.ros2.tasks]
ros2 = "python run.py mode=ROS2"

# yamcs-specific deps, tasks in feature "yamcs"
[feature.yamcs.pypi-dependencies]
yamcs-client = "*"

[feature.yamcs.tasks]
yamcs = "python run.py mode=Yamcs environment=lunaryard_40m_workshop robot=pragyaan controller=pragyaan-controller"
fix-tmp = "bash scripts/fix_yamcs_tmp.sh"

[feature.test-sim.dependencies]
python = "3.11.*"

[feature.test-sim.pypi-dependencies]
pytest = "*"
yamcs-client = "*"

[feature.test-sim.tasks]
test-ros2 = "pytest -v -s test/test_ros2_sanity.py"
test-yamcs = "pytest -v -s test/test_yamcs_sanity.py"

[environments]
default = { features = ["core", "isaac"] }
yamcs = { features = ["core", "isaac", "yamcs"] }
ros2 = { features = ["core", "isaac", "ros2"] }
test-sim = { features = ["test-sim"] }
ci = { features = ["core", "isaac", "ros2", "yamcs"] }
